version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: open-video-studio-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: open_video_studio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - open-video-studio-net

networks:
  open-video-studio-net:
    driver: bridge

volumes:
  postgres_data: